[workspace]
resolver = "2"
members = ["crates/supertask-core", "crates/supertask-cli", "crates/supertask-cloud-server", "src-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/shenlq1017/super-task"
homepage = "https://github.com/shenlq1017/super-task"
