//! httpd.conf 渲染（规格 §5.3 简化集）。
//!
//! 自包含最小 conf：ServerRoot/日志/PidFile 指向 `.supertask/gateway/`；
//! 最小 LoadModule 集（平台差异经 [`ApacheOptions`] 注入，不内置探测）；
//! ProxyPass 不剥前缀（与 nginx/caddy 同语义；`strip_prefix` 时用带尾斜杠
//! worker 显式剥除）；WebSocket 经 `ProxyPass … upgrade=websocket` 透传
//! （Apache 2.4.47+，本机校验失败会有明确 stderr）；CORS 用 `<Location>`
//! + `SetEnvIf` 白名单回显 + `mod_rewrite` preflight 204；静态站点
//! `DocumentRoot` + `Require all granted`；重定向 `Redirect`。

use crate::gateway::model::{GatewayCors, ResolvedGateway};

use super::{posix, sorted_locations};

/// unix（apt/brew 发行版）默认模块集。
pub static APACHE_MODULES_UNIX: &[(&str, &str)] = &[
    ("mpm_event_module", "mod_mpm_event.so"),
    ("unixd_module", "mod_unixd.so"),
    ("authz_core_module", "mod_authz_core.so"),
    ("log_config_module", "mod_log_config.so"),
    ("alias_module", "mod_alias.so"),
    ("proxy_module", "mod_proxy.so"),
    ("proxy_http_module", "mod_proxy_http.so"),
    ("headers_module", "mod_headers.so"),
    ("setenvif_module", "mod_setenvif.so"),
    ("rewrite_module", "mod_rewrite.so"),
    ("dir_module", "mod_dir.so"),
];

/// Windows（XAMPP / 官方 zip）默认模块集：mpm 用 winnt，无 unixd。
pub static APACHE_MODULES_WINDOWS: &[(&str, &str)] = &[
    ("mpm_winnt_module", "mod_mpm_winnt.so"),
    ("authz_core_module", "mod_authz_core.so"),
    ("log_config_module", "mod_log_config.so"),
    ("alias_module", "mod_alias.so"),
    ("proxy_module", "mod_proxy.so"),
    ("proxy_http_module", "mod_proxy_http.so"),
    ("headers_module", "mod_headers.so"),
    ("setenvif_module", "mod_setenvif.so"),
    ("rewrite_module", "mod_rewrite.so"),
    ("dir_module", "mod_dir.so"),
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ApacheOptions {
    /// conf/日志/PidFile 目录（正斜杠规范化由渲染负责）。
    pub dir: String,
    /// 模块目录（发行版 `modules/` / XAMPP `<apache>/modules`）。
    pub modules_dir: String,
    pub modules: &'static [(&'static str, &'static str)],
}

pub fn render_apache(ir: &ResolvedGateway, opts: &ApacheOptions) -> String {
    let dir = posix(&opts.dir);
    let modules_dir = posix(&opts.modules_dir);
    let listen = format!("127.0.0.1:{}", ir.port);
    let mut out = String::new();
    out.push_str(
        "# Generated by SuperTask — source of truth is supertask.yaml (gateway section).\n",
    );
    out.push_str("# This file is regenerated on gateway start/apply; do not edit.\n");
    out.push_str("# SuperTask: WebSocket 转发经 ProxyPass upgrade=websocket（Apache 2.4.47+）。\n");
    out.push_str("ServerName localhost\n");
    out.push_str(&format!("ServerRoot \"{dir}\"\n"));
    out.push_str(&format!("PidFile \"{dir}/httpd.pid\"\n"));
    out.push_str(&format!("ErrorLog \"{dir}/httpd-error.log\"\n"));
    out.push_str("LogLevel warn\n");
    out.push_str(&format!("CustomLog \"{dir}/httpd-access.log\" common\n"));
    out.push('\n');
    for (name, file) in opts.modules {
        out.push_str(&format!("LoadModule {name} \"{modules_dir}/{file}\"\n"));
    }
    out.push('\n');
    out.push_str(&format!("Listen {listen}\n\n"));
    out.push_str("ProxyRequests Off\n");
    out.push_str("ProxyPreserveHost On\n\n");
    let catch_all = ir.groups.iter().find(|g| g.host.is_none());
    for group in &ir.groups {
        out.push_str(&format!("<VirtualHost {listen}>\n"));
        let hosts: Vec<&str> = match &group.host {
            Some(host) => host.split(", ").collect(),
            None => vec!["localhost"],
        };
        out.push_str(&format!("    ServerName {}\n", hosts[0]));
        if hosts.len() > 1 {
            out.push_str(&format!("    ServerAlias {}\n", hosts[1..].join(" ")));
        }
        out.push('\n');
        // 静态站点（path=/）：DocumentRoot + 目录授权
        for loc in &group.locations {
            if let Some(d) = &loc.static_dir {
                out.push_str(&format!("    DocumentRoot \"{}\"\n", posix(d)));
                out.push_str(&format!("    <Directory \"{}\">\n", posix(d)));
                out.push_str("        Require all granted\n");
                out.push_str("    </Directory>\n");
            }
        }
        // CORS：<Location> 内 SetEnvIf 白名单回显 + Header（按路由隔离环境变量）
        let mut cors_vars: Vec<(String, String)> = Vec::new(); // (env var, path)
        for loc in sorted_locations(&group.locations) {
            if let Some(cors) = &loc.cors {
                if loc.upstream.is_some() {
                    let var = format!("CORS_ORIGIN_{}", cors_vars.len());
                    out.push_str(&format!("    <Location \"{}\">\n", loc.path));
                    push_apache_cors(&mut out, &var, cors);
                    out.push_str("    </Location>\n");
                    cors_vars.push((var, loc.path.clone()));
                }
            }
        }
        if !cors_vars.is_empty() {
            // preflight 本地 204：Origin 命中白名单（env 已设）才拦，其余 OPTIONS 照常转发
            out.push_str("    RewriteEngine On\n");
            for (var, path) in &cors_vars {
                out.push_str("    RewriteCond %{REQUEST_METHOD} =OPTIONS\n");
                out.push_str(&format!("    RewriteCond %{{ENV:{var}}} !^$\n"));
                out.push_str(&format!(
                    "    RewriteRule ^{}(/.*)?$ - [R=204,L]\n",
                    regex_escape(path)
                ));
            }
            out.push('\n');
        }
        // 路由：Redirect 在前，ProxyPass 在后（最长前缀优先）
        for loc in sorted_locations(&group.locations) {
            if let Some(rd) = &loc.redirect {
                out.push_str(&format!(
                    "    Redirect {} {} {}\n",
                    rd.status, loc.path, rd.to
                ));
            }
        }
        for loc in sorted_locations(&group.locations) {
            let Some(upstream) = &loc.upstream else {
                continue;
            };
            // strip_prefix：worker 带尾斜杠 → location 前缀被剥除；
            // upgrade=websocket：Upgrade 请求透传为 WS 隧道（Apache 2.4.47+），
            // 普通 HTTP 请求不受影响（三引擎行为一致）。
            let worker = if loc.strip_prefix {
                format!("{}/", upstream.url())
            } else {
                format!("{}{}", upstream.url(), loc.path)
            };
            out.push_str(&format!(
                "    ProxyPass {} {} upgrade=websocket\n",
                loc.path, worker
            ));
            out.push_str(&format!("    ProxyPassReverse {} {}\n", loc.path, worker));
        }
        out.push_str("</VirtualHost>\n\n");
    }
    if catch_all.is_none() {
        // 无 catch-all：首个 vhost 会兜住未匹配 host 的请求——显式 404 兜底块
        out.push_str("<VirtualHost ");
        out.push_str(&listen);
        out.push_str(">\n");
        out.push_str("    ServerName fallback.invalid\n");
        out.push_str("    RedirectMatch 404 ^\n");
        out.push_str("</VirtualHost>\n");
    }
    let trimmed = out.trim_end_matches('\n');
    format!("{trimmed}\n")
}

/// `<Location>` 内的 CORS 头组：SetEnvIf 白名单回显（未命中不发头）。
fn push_apache_cors(out: &mut String, var: &str, cors: &GatewayCors) {
    let pattern = if cors.origins.len() == 1 && cors.origins[0] == "*" {
        "^(.+)$".to_string()
    } else {
        let alts: Vec<String> = cors.origins.iter().map(|o| regex_escape(o)).collect();
        format!("^({})$", alts.join("|"))
    };
    out.push_str(&format!("        SetEnvIf Origin \"{pattern}\" {var}=$1\n"));
    out.push_str(&format!(
        "        Header always set Access-Control-Allow-Origin \"%{{{var}}}e\" env={var}\n"
    ));
    out.push_str(&format!(
        "        Header always set Access-Control-Allow-Methods \"{}\" env={var}\n",
        cors.methods_csv()
    ));
    out.push_str(&format!(
        "        Header always set Access-Control-Allow-Headers \"{}\" env={var}\n",
        cors.headers_csv()
    ));
    out.push_str(&format!(
        "        Header always set Access-Control-Max-Age \"{}\" env={var}\n",
        cors.max_age_secs
    ));
    if cors.credentials {
        out.push_str(&format!(
            "        Header always set Access-Control-Allow-Credentials \"true\" env={var}\n"
        ));
    }
}

/// mod_rewrite pattern / mod_setenvif 正则的元字符转义。
fn regex_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if matches!(
            c,
            '.' | '^' | '$' | '|' | '(' | ')' | '[' | ']' | '{' | '}' | '*' | '+' | '?' | '\\'
        ) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gateway::model::resolve;
    use crate::spec::parse_yaml;

    fn ir_of(gateway_yaml: &str, services: &str) -> ResolvedGateway {
        let text = format!("version: 1\nservices:\n{services}\ngateway:\n{gateway_yaml}");
        let (f, _) = parse_yaml(&text).unwrap();
        let conf = f.gateway.clone().unwrap();
        resolve(&f, &conf, &|_| "127.0.0.1".into(), "C:/ws").unwrap()
    }

    const SERVICES: &str = "  user-api:\n    kind: spring-boot\n    module: api\n    port: 8081\n  web:\n    kind: node\n    dir: web\n    port: 5173\n";

    fn opts(dir: &str, modules: &'static [(&'static str, &'static str)]) -> ApacheOptions {
        ApacheOptions {
            dir: dir.into(),
            modules_dir: "C:/xampp/apache/modules".into(),
            modules,
        }
    }

    fn golden(name: &str, text: &str) {
        let path = format!("tests/golden/gateway/{name}");
        match std::fs::read_to_string(&path) {
            Ok(want) => assert_eq!(
                text,
                want.replace("\r\n", "\n"),
                "golden {name} 不一致（更新请重写 golden 文件）"
            ),
            Err(_) => {
                let _ = std::fs::create_dir_all("tests/golden/gateway");
                std::fs::write(&path, text).unwrap();
                panic!("golden {name} 已生成，请重跑测试确认");
            }
        }
    }

    #[test]
    fn golden_apache_windows_modules() {
        let ir = ir_of(
            "  kind: apache\n  port: 8080\n  routes:\n    - path: /api\n      target: user-api\n    - path: /\n      target: web\n",
            SERVICES,
        );
        golden(
            "apache-win.txt",
            &render_apache(
                &ir,
                &opts("C:/ws/.supertask/gateway", APACHE_MODULES_WINDOWS),
            ),
        );
    }

    #[test]
    fn golden_apache_unix_modules_host_group() {
        let ir = ir_of(
            "  kind: apache\n  port: 8080\n  routes:\n    - host: api.localhost\n      path: /\n      target: user-api\n    - path: /\n      target: web\n",
            SERVICES,
        );
        golden(
            "apache-unix.txt",
            &render_apache(&ir, &opts("C:/ws/.supertask/gateway", APACHE_MODULES_UNIX)),
        );
    }

    #[test]
    fn apache_no_catch_all_gets_404_vhost_and_longest_prefix_first() {
        // 全部路由带 host → 无 catch-all 组 → 需要 404 兜底 vhost
        let ir = ir_of(
            "  kind: apache\n  port: 8080\n  routes:\n    - host: a.localhost\n      path: /api\n      target: user-api\n    - host: a.localhost\n      path: /api/v2\n      target: web\n",
            SERVICES,
        );
        let text = render_apache(
            &ir,
            &opts("C:/ws/.supertask/gateway", APACHE_MODULES_WINDOWS),
        );
        assert!(text.contains("RedirectMatch 404 ^"), "{text}");
        // ProxyPass 先匹配先生效：/api/v2 必须排在 /api 之前
        let idx_v2 = text.find("ProxyPass /api/v2 ").unwrap();
        let idx_api = text.find("ProxyPass /api ").unwrap();
        assert!(idx_v2 < idx_api);
    }

    #[test]
    fn apache_ws_upgrade_present() {
        let ir = ir_of(
            "  kind: apache\n  port: 8080\n  routes:\n    - path: /api\n      target: user-api\n",
            SERVICES,
        );
        let text = render_apache(
            &ir,
            &opts("C:/ws/.supertask/gateway", APACHE_MODULES_WINDOWS),
        );
        assert!(
            text.contains("ProxyPass /api http://127.0.0.1:8081/api upgrade=websocket"),
            "{text}"
        );
    }

    #[test]
    fn golden_apache_tunnel_features() {
        // 多域名别名 + strip_prefix + CORS（含点号，检验正则转义）+ 静态站点 + 重定向
        let ir = ir_of(
            "  kind: apache\n  port: 8080\n  routes:\n    - host: \"api.localhost, api2.localhost\"\n      path: /api\n      target: user-api\n      strip_prefix: true\n      cors:\n        origins:\n          - http://app.dev:3000\n          - http://app.dev:5173\n        credentials: true\n    - path: /\n      static_dir: web/dist\n    - path: /old\n      redirect: /new\n      redirect_status: 308\n",
            SERVICES,
        );
        let text = render_apache(
            &ir,
            &opts("C:/ws/.supertask/gateway", APACHE_MODULES_WINDOWS),
        );
        golden("apache-tunnel-features.txt", &text);
        assert!(text.contains("ServerName api.localhost"));
        assert!(text.contains("ServerAlias api2.localhost"));
        assert!(text.contains("ProxyPass /api http://127.0.0.1:8081/"));
        assert!(text.contains("DocumentRoot \"C:/ws/web/dist\""));
        assert!(text.contains("Redirect 308 /old /new"));
        assert!(
            text.contains("SetEnvIf Origin \"^(http://app\\.dev:3000|http://app\\.dev:5173)$\" CORS_ORIGIN_0=$1"),
            "{text}"
        );
        assert!(text.contains("RewriteRule ^/api(/.*)?$ - [R=204,L]"));
    }
}
