//! httpd.conf 渲染（规格 §5.3 简化集）。
//!
//! 自包含最小 conf：ServerRoot/日志/PidFile 指向 `.supertask/gateway/`；
//! 最小 LoadModule 集（平台差异经 [`ApacheOptions`] 注入，不内置探测）；
//! ProxyPass 不剥前缀（与 nginx/caddy 同语义）；WebSocket 不转发——注释行
//! 供 UI 提示对齐。

use crate::gateway::model::ResolvedGateway;

use super::{posix, sorted_locations};

/// unix（apt/brew 发行版）默认模块集。
pub static APACHE_MODULES_UNIX: &[(&str, &str)] = &[
    ("mpm_event_module", "mod_mpm_event.so"),
    ("unixd_module", "mod_unixd.so"),
    ("authz_core_module", "mod_authz_core.so"),
    ("log_config_module", "mod_log_config.so"),
    ("alias_module", "mod_alias.so"),
    ("proxy_module", "mod_proxy.so"),
    ("proxy_http_module", "mod_proxy_http.so"),
    ("headers_module", "mod_headers.so"),
];

/// Windows（XAMPP / 官方 zip）默认模块集：mpm 用 winnt，无 unixd。
pub static APACHE_MODULES_WINDOWS: &[(&str, &str)] = &[
    ("mpm_winnt_module", "mod_mpm_winnt.so"),
    ("authz_core_module", "mod_authz_core.so"),
    ("log_config_module", "mod_log_config.so"),
    ("alias_module", "mod_alias.so"),
    ("proxy_module", "mod_proxy.so"),
    ("proxy_http_module", "mod_proxy_http.so"),
    ("headers_module", "mod_headers.so"),
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ApacheOptions {
    /// conf/日志/PidFile 目录（正斜杠规范化由渲染负责）。
    pub dir: String,
    /// 模块目录（发行版 `modules/` / XAMPP `<apache>/modules`）。
    pub modules_dir: String,
    pub modules: &'static [(&'static str, &'static str)],
}

pub fn render_apache(ir: &ResolvedGateway, opts: &ApacheOptions) -> String {
    let dir = posix(&opts.dir);
    let modules_dir = posix(&opts.modules_dir);
    let listen = format!("127.0.0.1:{}", ir.port);
    let mut out = String::new();
    out.push_str(
        "# Generated by SuperTask — source of truth is supertask.yaml (gateway section).\n",
    );
    out.push_str("# This file is regenerated on gateway start/apply; do not edit.\n");
    out.push_str("# SuperTask: Apache 简化集不转发 WebSocket（mod_proxy_wstunnel 未启用）。\n");
    out.push_str("ServerName localhost\n");
    out.push_str(&format!("ServerRoot \"{dir}\"\n"));
    out.push_str(&format!("PidFile \"{dir}/httpd.pid\"\n"));
    out.push_str(&format!("ErrorLog \"{dir}/httpd-error.log\"\n"));
    out.push_str("LogLevel warn\n");
    out.push_str(&format!("CustomLog \"{dir}/httpd-access.log\" common\n"));
    out.push('\n');
    for (name, file) in opts.modules {
        out.push_str(&format!("LoadModule {name} \"{modules_dir}/{file}\"\n"));
    }
    out.push('\n');
    out.push_str(&format!("Listen {listen}\n\n"));
    out.push_str("ProxyRequests Off\n");
    out.push_str("ProxyPreserveHost On\n\n");
    let catch_all = ir.groups.iter().find(|g| g.host.is_none());
    for group in &ir.groups {
        out.push_str(&format!("<VirtualHost {listen}>\n"));
        match &group.host {
            Some(host) => out.push_str(&format!("    ServerName {host}\n")),
            None => out.push_str("    ServerName localhost\n"),
        }
        out.push('\n');
        for loc in sorted_locations(&group.locations) {
            let upstream = format!("{}{}", loc.upstream.url(), loc.path);
            out.push_str(&format!("    ProxyPass {} {}\n", loc.path, upstream));
            out.push_str(&format!("    ProxyPassReverse {} {}\n", loc.path, upstream));
        }
        out.push_str("</VirtualHost>\n\n");
    }
    if catch_all.is_none() {
        // 无 catch-all：首个 vhost 会兜住未匹配 host 的请求——显式 404 兜底块
        out.push_str("<VirtualHost ");
        out.push_str(&listen);
        out.push_str(">\n");
        out.push_str("    ServerName fallback.invalid\n");
        out.push_str("    RedirectMatch 404 ^\n");
        out.push_str("</VirtualHost>\n");
    }
    let trimmed = out.trim_end_matches('\n');
    format!("{trimmed}\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gateway::model::resolve;
    use crate::spec::parse_yaml;

    fn ir_of(gateway_yaml: &str, services: &str) -> ResolvedGateway {
        let text = format!("version: 1\nservices:\n{services}\ngateway:\n{gateway_yaml}");
        let (f, _) = parse_yaml(&text).unwrap();
        let conf = f.gateway.clone().unwrap();
        resolve(&f, &conf, &|_| "127.0.0.1".into()).unwrap()
    }

    const SERVICES: &str = "  user-api:\n    kind: spring-boot\n    module: api\n    port: 8081\n  web:\n    kind: node\n    dir: web\n    port: 5173\n";

    fn opts(dir: &str, modules: &'static [(&'static str, &'static str)]) -> ApacheOptions {
        ApacheOptions {
            dir: dir.into(),
            modules_dir: "C:/xampp/apache/modules".into(),
            modules,
        }
    }

    fn golden(name: &str, text: &str) {
        let path = format!("tests/golden/gateway/{name}");
        match std::fs::read_to_string(&path) {
            Ok(want) => assert_eq!(
                text,
                want.replace("\r\n", "\n"),
                "golden {name} 不一致（更新请重写 golden 文件）"
            ),
            Err(_) => {
                let _ = std::fs::create_dir_all("tests/golden/gateway");
                std::fs::write(&path, text).unwrap();
                panic!("golden {name} 已生成，请重跑测试确认");
            }
        }
    }

    #[test]
    fn golden_apache_windows_modules() {
        let ir = ir_of(
            "  kind: apache\n  port: 8080\n  routes:\n    - path: /api\n      target: user-api\n    - path: /\n      target: web\n",
            SERVICES,
        );
        golden(
            "apache-win.txt",
            &render_apache(
                &ir,
                &opts("C:/ws/.supertask/gateway", APACHE_MODULES_WINDOWS),
            ),
        );
    }

    #[test]
    fn golden_apache_unix_modules_host_group() {
        let ir = ir_of(
            "  kind: apache\n  port: 8080\n  routes:\n    - host: api.localhost\n      path: /\n      target: user-api\n    - path: /\n      target: web\n",
            SERVICES,
        );
        golden(
            "apache-unix.txt",
            &render_apache(&ir, &opts("C:/ws/.supertask/gateway", APACHE_MODULES_UNIX)),
        );
    }

    #[test]
    fn apache_no_catch_all_gets_404_vhost_and_longest_prefix_first() {
        // 全部路由带 host → 无 catch-all 组 → 需要 404 兜底 vhost
        let ir = ir_of(
            "  kind: apache\n  port: 8080\n  routes:\n    - host: a.localhost\n      path: /api\n      target: user-api\n    - host: a.localhost\n      path: /api/v2\n      target: web\n",
            SERVICES,
        );
        let text = render_apache(
            &ir,
            &opts("C:/ws/.supertask/gateway", APACHE_MODULES_WINDOWS),
        );
        assert!(text.contains("RedirectMatch 404 ^"), "{text}");
        // ProxyPass 先匹配先生效：/api/v2 必须排在 /api 之前
        let idx_v2 = text.find("ProxyPass /api/v2 ").unwrap();
        let idx_api = text.find("ProxyPass /api ").unwrap();
        assert!(idx_v2 < idx_api);
    }

    #[test]
    fn apache_ws_notice_comment_present() {
        let ir = ir_of(
            "  kind: apache\n  port: 8080\n  routes:\n    - path: /\n      target: web\n",
            SERVICES,
        );
        let text = render_apache(
            &ir,
            &opts("C:/ws/.supertask/gateway", APACHE_MODULES_WINDOWS),
        );
        assert!(text.contains("不转发 WebSocket"));
    }
}
