//! Caddyfile 渲染（规格 §5.2）。
//!
//! 全局 `admin off`（避免 2019 端口冲突；停止走进程树，不经 admin API）；
//! `tls internal` → 站点地址 `https://…` + 块内 `tls internal`；路由用命名
//! matcher + `handle`（同站点互斥），按最长前缀声明；空 host 组用
//! `localhost` 站点地址（浏览器对 `*.localhost` 内建直连 127.0.0.1）。

use crate::gateway::model::ResolvedGateway;

use super::{has_root, sorted_locations};

pub fn render_caddy(ir: &ResolvedGateway) -> String {
    let scheme = if ir.tls == crate::spec::GatewayTls::Internal {
        "https"
    } else {
        "http"
    };
    let mut out = String::new();
    out.push_str("# Generated by SuperTask — source of truth is supertask.yaml (gateway section).\n");
    out.push_str("# This file is regenerated on gateway start/apply; do not edit.\n");
    out.push_str("{\n\tadmin off\n}\n\n");
    for group in &ir.groups {
        let site = match &group.host {
            Some(host) => format!("{scheme}://{host}:{}", ir.port),
            None => format!("{scheme}://localhost:{}", ir.port),
        };
        out.push_str(&format!("{site} {{\n"));
        if ir.tls == crate::spec::GatewayTls::Internal {
            out.push_str("\ttls internal\n");
        }
        let has_root_route = has_root(&group.locations);
        for (i, loc) in sorted_locations(&group.locations).iter().enumerate() {
            if loc.path == "/" {
                // 根路由 = 站点 catch-all handle
                out.push_str("\thandle {\n");
                out.push_str(&format!("\t\treverse_proxy {}\n", loc.upstream.url()));
                out.push_str("\t}\n");
                continue;
            }
            out.push_str(&format!("\t@r{i} path {p} {p}/*\n", p = loc.path));
            out.push_str(&format!("\thandle @r{i} {{\n"));
            out.push_str(&format!("\t\treverse_proxy {}\n", loc.upstream.url()));
            out.push_str("\t}\n");
        }
        if !has_root_route {
            out.push_str("\thandle {\n\t\trespond \"Not Found\" 404\n\t}\n");
        }
        out.push_str("}\n\n");
    }
    let trimmed = out.trim_end_matches('\n');
    format!("{trimmed}\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gateway::model::resolve;
    use crate::spec::parse_yaml;

    fn ir_of(gateway_yaml: &str, services: &str) -> ResolvedGateway {
        let text = format!("version: 1\nservices:\n{services}\ngateway:\n{gateway_yaml}");
        let (f, _) = parse_yaml(&text).unwrap();
        let conf = f.gateway.clone().unwrap();
        resolve(&f, &conf, &|_| "127.0.0.1".into()).unwrap()
    }

    const SERVICES: &str = "  user-api:\n    kind: spring-boot\n    module: api\n    port: 8081\n  web:\n    kind: node\n    dir: web\n    port: 5173\n";

    fn golden(name: &str, text: &str) {
        let path = format!("tests/golden/gateway/{name}");
        match std::fs::read_to_string(&path) {
            Ok(want) => assert_eq!(text, want, "golden {name} 不一致（更新请重写 golden 文件）"),
            Err(_) => {
                let _ = std::fs::create_dir_all("tests/golden/gateway");
                std::fs::write(&path, text).unwrap();
                panic!("golden {name} 已生成，请重跑测试确认");
            }
        }
    }

    #[test]
    fn golden_caddy_tls_off_with_routes() {
        let ir = ir_of(
            "  kind: caddy\n  port: 8443\n  routes:\n    - path: /api\n      target: user-api\n    - path: /\n      target: web\n",
            SERVICES,
        );
        golden("caddy-off.txt", &render_caddy(&ir));
    }

    #[test]
    fn golden_caddy_tls_internal_host_group() {
        let ir = ir_of(
            "  kind: caddy\n  port: 8443\n  tls: internal\n  routes:\n    - host: api.localhost\n      path: /\n      target: user-api\n    - path: /\n      target: web\n",
            SERVICES,
        );
        golden("caddy-internal.txt", &render_caddy(&ir));
    }

    #[test]
    fn caddy_no_root_route_gets_404_handle() {
        let ir = ir_of(
            "  kind: caddy\n  port: 8080\n  routes:\n    - path: /api\n      target: user-api\n",
            SERVICES,
        );
        let text = render_caddy(&ir);
        assert!(text.contains("respond \"Not Found\" 404"), "{text}");
    }
}
