//! nginx.conf 渲染（规格 §5.1 白名单指令集）。
//!
//! 关键行为：`daemon off` 前台运行（进程树托管必需）；空 host 组 =
//! `default_server`；无 catch-all 组时输出 404 兜底 server；WebSocket
//! 升级头透传（Vite HMR 可用）。

use crate::gateway::model::ResolvedGateway;

use super::{posix, sorted_locations};

pub fn render_nginx(ir: &ResolvedGateway, dir: &str) -> String {
    let dir = posix(dir);
    let listen = format!("127.0.0.1:{}", ir.port);
    let mut out = String::new();
    out.push_str("# Generated by SuperTask — source of truth is supertask.yaml (gateway section).\n");
    out.push_str("# This file is regenerated on gateway start/apply; do not edit.\n");
    out.push_str("worker_processes 1;\n");
    out.push_str("daemon off;\n");
    out.push_str(&format!("pid \"{dir}/nginx.pid\";\n"));
    out.push_str(&format!("error_log \"{dir}/nginx-error.log\";\n"));
    out.push_str("\nevents {\n    worker_connections 1024;\n}\n");
    out.push_str("\nhttp {\n");
    out.push_str(&format!("    access_log \"{dir}/nginx-access.log\";\n"));
    out.push_str("    sendfile on;\n");
    out.push_str("    map $http_upgrade $connection_upgrade {\n");
    out.push_str("        default upgrade;\n");
    out.push_str("        ''      close;\n");
    out.push_str("    }\n\n");

    let catch_all = ir.groups.iter().find(|g| g.host.is_none());
    if catch_all.is_none() {
        // 无 catch-all：显式 404 兜底（未命中任何 host 的请求不串到别的 server）
        out.push_str("    server {\n");
        out.push_str(&format!("        listen {listen} default_server;\n"));
        out.push_str("        server_name _;\n");
        out.push_str("        return 404;\n");
        out.push_str("    }\n\n");
    }
    for group in &ir.groups {
        out.push_str("    server {\n");
        match &group.host {
            Some(host) => {
                out.push_str(&format!("        listen {listen};\n"));
                out.push_str(&format!("        server_name {host};\n"));
            }
            None => {
                out.push_str(&format!("        listen {listen} default_server;\n"));
                out.push_str("        server_name _;\n");
            }
        }
        out.push('\n');
        for loc in sorted_locations(&group.locations) {
            out.push_str(&format!("        location {} {{\n", loc.path));
            out.push_str(&format!(
                "            proxy_pass {};\n",
                loc.upstream.url()
            ));
            out.push_str("            proxy_http_version 1.1;\n");
            out.push_str("            proxy_set_header Host $host;\n");
            out.push_str("            proxy_set_header X-Real-IP $remote_addr;\n");
            out.push_str("            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n");
            out.push_str("            proxy_set_header X-Forwarded-Proto $scheme;\n");
            out.push_str("            proxy_set_header Upgrade $http_upgrade;\n");
            out.push_str("            proxy_set_header Connection $connection_upgrade;\n");
            out.push_str("        }\n");
        }
        out.push_str("    }\n");
    }
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gateway::model::{resolve, UpstreamAddr};
    use crate::spec::{parse_yaml, GatewayKind, GatewayTls};

    fn ir_of(gateway_yaml: &str, services: &str) -> ResolvedGateway {
        let text = format!("version: 1\nservices:\n{services}\ngateway:\n{gateway_yaml}");
        let (f, _) = parse_yaml(&text).unwrap();
        let conf = f.gateway.clone().unwrap();
        resolve(&f, &conf, &|_| "127.0.0.1".into()).unwrap()
    }

    const SERVICES: &str = "  user-api:\n    kind: spring-boot\n    module: api\n    port: 8081\n  web:\n    kind: node\n    dir: web\n    port: 5173\n";

    fn golden(name: &str, text: &str) {
        let path = format!("tests/golden/gateway/{name}");
        match std::fs::read_to_string(&path) {
            Ok(want) => assert_eq!(text, want, "golden {name} 不一致（更新请重写 golden 文件）"),
            Err(_) => {
                let _ = std::fs::create_dir_all("tests/golden/gateway");
                std::fs::write(&path, text).unwrap();
                panic!("golden {name} 已生成，请重跑测试确认");
            }
        }
    }

    #[test]
    fn golden_nginx_single_route() {
        let ir = ir_of(
            "  kind: nginx\n  port: 8080\n  routes:\n    - path: /api\n      target: user-api\n    - path: /\n      target: web\n",
            SERVICES,
        );
        golden("nginx-single.txt", &render_nginx(&ir, "C:/ws/.supertask/gateway"));
    }

    #[test]
    fn golden_nginx_host_groups_and_catch_all() {
        let ir = ir_of(
            "  kind: nginx\n  port: 8080\n  routes:\n    - host: api.localhost\n      path: /\n      target: user-api\n    - path: /\n      target: web\n",
            SERVICES,
        );
        golden("nginx-hosts.txt", &render_nginx(&ir, "C:/ws/.supertask/gateway"));
    }

    #[test]
    fn golden_nginx_no_catch_all_404_and_longest_prefix_first() {
        // 全部路由带 host → 无 catch-all 组 → 显式 404 兜底 server
        let ir = ir_of(
            "  kind: nginx\n  port: 8080\n  routes:\n    - host: api.localhost\n      path: /api\n      target: user-api\n    - host: api.localhost\n      path: /api/v2\n      target: web\n",
            SERVICES,
        );
        let text = render_nginx(&ir, "C:/ws/.supertask/gateway");
        golden("nginx-404.txt", &text);
        assert!(text.contains("return 404;"));
        assert_eq!(text.matches("default_server").count(), 1);
    }

    #[test]
    fn nginx_ipv6_upstream_rendered_with_brackets() {
        let mut ir = ir_of(
            "  kind: nginx\n  port: 8080\n  routes:\n    - path: /\n      target: web\n",
            SERVICES,
        );
        ir.groups[0].locations[0].upstream = UpstreamAddr {
            host: "[::1]".into(),
            port: 5173,
        };
        let text = render_nginx(&ir, "/ws/.supertask/gateway");
        assert!(text.contains("proxy_pass http://[::1]:5173;"), "{text}");
    }

    #[test]
    fn nginx_tls_is_nginx_ignored_but_kind_field_preserved() {
        let ir = ir_of(
            "  kind: nginx\n  tls: internal\n  port: 8080\n  routes:\n    - path: /\n      target: web\n",
            SERVICES,
        );
        assert_eq!(ir.tls, GatewayTls::Internal);
        assert_eq!(ir.kind, GatewayKind::Nginx);
        let text = render_nginx(&ir, "C:/ws/.supertask/gateway");
        assert!(!text.contains("tls"));
    }
}
